name: My first workflow

on: [push]

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 

            - name: checkout repo
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "My github actions job"

            - name: directory
              run: |
                pwd
                ls -lart
                ls -ltra
                cat README.md
            
            - name: Generate ASCII Artwork
              run: cowsay -f "Run for cover I am dragon" >> gragon.txt

            - name: Create file
              run: touch script.sh

