name: My first workflow

on: [push]

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
            - name: welcome message
              run: echo "My github actions job"

            - name: directory
              run: pwd

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md