name: Generates ASCII

on: [push]

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps: 

            - name: checkout repo
              uses: actions/checkout@v4

            - name: Excecute bash script
              run: |
               chmod +x script.sh
               ./script.sh

