name: Generates ASCII

on: [push]

jobs: 
    ascii_job: 
        runs-on: ubuntu-latest
        steps: 

            - name: checkout repo
              uses: actions/checkout@v4

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: Excecute ASCII Artwork command
              run: cowsay -f dragon "Run for cover I am dragon" >> dragon.txt

            - name: Read file
              run: cat dragon.txt
            
            - name: Checkout repo files
              run: ls -lart

